### PR TITLE
Started adding UnitTests

### PR DESCRIPTION
**Pull request by tidusjar**
Added UnitTests to the solution.

I will keep adding more as I go :+1:

### CODE REVIEW

**Comment by bbougot** [comment]
That's great! Many thanks for your contribution :+1:

**Comment by tidusjar** [comment]
No problem, is there anything i can help out with?

**Comment by bbougot** [comment]
I'm focusing on an annoying issue related to Vlc.DotNet (https://github.com/ZeBobo5/Vlc.DotNet) which is the current media player of the project. 
I detailed the issue here : https://github.com/bbougot/Yak/issues/4
Feel free to look into this issue. I'm also planning to make a trello in order to list the upcoming new features.

**Comment by tidusjar** [comment]
OK! I have a problem that the application wont actually load for me and I cannot work out why. It just stays on MainWindow and loads.

**Comment by bbougot** [comment]
Hmm.. If you set a breakpoint l.197 in the LoadNextPage of the MoviesViewModel class, does it return a list of movies ?

**Comment by tidusjar** [comment]
I will do this when I get home from work!

**Pull request merged**
